# Generated by Django 4.2 on 2023-05-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('fio', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=50)),
                ('home_address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=11)),
                ('mail', models.CharField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
